import Head from 'next/head'
import Heatmap from '@react-sandbox/heatmap'
import { values } from '@/lib/data'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <div style={{ width: '100%' }}>
          <Heatmap
            startDate={new Date('2022-12-30T00:00:00')}
            values={values}
            scaleFactor={35}
          />
        </div>
      </main>
    </>
  )
}
